web :
  build: .
  ports: 8080:8080
  links: mysql

mysql :
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: boot
    MYSQL_USER: user
    MYSQL_PASSWORD: pwd
  volume:/var/lib/mysql
